baseURL = "/"
languageCode = "en-gb"
title = "Fullstack Digital / Brand, Web, Market"
theme = ["fullstackdigital","pancakes-builder"]

enableRobotsTXT = true
disableAliases = true

[permalinks]
  pages = "/:section/:title/"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "blog.fullstackdigital.com"
  weight = 3

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "blog.fullstackdigital.com"
  weight = 2

[[menu.main]]
parent = "About"
identifier = "about"
name = "About"
url = "blog.fullstackdigital.com"
weight = 2

[params]
disallow_search_engines = false # set robots.txt to disallow everything

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

