baseURL = ""
languageCode = "en-us"
title = "Fullstack Digital"
theme = ["pancakes-builder"]
[params]
cloudinary_base = "https://res.cloudinary.com/dzttfmzl7/image/upload/"
cloudinary_folder = "pancakes"
cloudinary_name = "dzttfmzl7"
postcss_testing = false