[build]
    command = "hugo --minify"
    publish = "public"
    functions = "functions"

[build.environment]
    HUGO_VERSION = "0.55.6"

[context.production.environment]
    HUGO_ENV = "development"
    NODE_ENV = "production"

[context.deploy-preview]
    command = "npm run build:preview"
