---
label: Home
hide_body: true
fields:
- name: seo
  type: include
  config: {}
  template: partial
  label: SEO
  description: Seo partial
- name: sections
  type: include
  config: {}
  template: partial-section-repeater
  label: Sections
