---
label: Home
hide_body: true
fields:
- name: seo
  type: include
  config: {}
  template: partial
  label: SEO
  description: Seo partial
- name: sections
  type: blocks
  label: Sections
  template_types:
  - query-work-items
  config:
    min: 
    max: 
pages:
- content/_index.md
